#!/data/data/com.termux/files/usr/bin/env bash
# setup all files for you

# Start message
echo "Script start ... "

# Change directory to HOME
cd $HOME

# Move old files
mv .vimrc .old-vimrc
mv .tmux.conf .old-tmux-conf
mv .bashrc .old-bashrc

# Back to dotfile directory
cd - > /dev/null
cp -rf .vimrc .tmux.conf .bashrc $HOME/

# Goodbye message
echo "Script Finished :-)"
